kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: nutanix-volume
{{- if eq .Values.defaultStorageClass "volume" }}
    annotations:
        storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: com.nutanix.csi
parameters:
    csiProvisionerSecretName: ntnx-secret
    csiProvisionerSecretNamespace: default
    csiNodePublishSecretName: ntnx-secret
    csiNodePublishSecretNamespace: default
    dataServiceEndPoint: {{ .Values.dataServiceEndPoint }}
    storageContainer: {{ .Values.storageContainer }}
    fsType: {{ .Values.fsType }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: nutanix-file
{{- if eq .Values.defaultStorageClass "file" }}
    annotations:
        storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: com.nutanix.csi
parameters:
    nfsServer: {{ .Values.fileHost }}
    nfsPath: {{ .Values.filePath }}

